name: pythia-book-dev
channels:
  - conda-forge
dependencies:
  - cartopy
  - jupyter-book
  - jupyterlab
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numpy
  - pip
  - pre-commit
  - dask
  - pyproj
  - pythia-datasets
  - python
  - scipy
  - ffmpeg
  - xarray
  - python-graphviz
  - graphviz
  - setuptools>=69.0.3
  - pip:
    - sphinx-pythia-theme
