name: pythia-book-dev
channels:
  - conda-forge
  - ncar
dependencies:
  - python=3.8
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - pre-commit
  - sqlalchemy<1.4
  - cartopy
  - xarray
  - netcdf4
  - pyproj
  - pythia-datasets
  - scipy
  - ffmpeg
