name: pythia-book-dev
channels:
  - conda-forge
dependencies:
  - cartopy
  - jupyter-book
  - jupyterlab
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numpy
  - pre-commit
  - dask
  - pyproj
  - pythia-datasets
  - python<3.12  # Waiting on https://github.com/jupyter/jupyter_events/issues/99
  - scipy
  - ffmpeg
  - xarray
  - python-graphviz
  - graphviz
  - setuptools
  - sphinx-pythia-theme
