name: pythia-book-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - pre-commit
  - sqlalchemy<1.4
  - cartopy
  - xarray
  - netcdf4
  - pyproj
  - scipy
  - wrf-python
  - netcdf4
  - pip
  - pip:
      # works for regular pip packages
      - pythia-datasets
