name: trigger-link-check
on:
  pull_request:

jobs:
  link-check:
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
    with:
      build_command: 'myst build --check-links --strict'
